name: Docker Deploy on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mil05/portfolio-site:${{  }} .

      - name: upload image to dockerhub
        run: docker build -t mil05/portfolio-site:${{  }} .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

      - name: Upload image to server
        run: scp astro-app.tar.gz user@your.server.ip:/tmp/

      - name: Load and run container on server
        run: |
          ssh user@your.server.ip << 'EOF'
          docker load < /tmp/astro-app.tar.gz
          docker stop astro-app || true && docker rm astro-app || true
          docker run -d --name astro-app -p 80:80 --restart always astro-app
          EOF
